services:
  - type: web
    name: pedagogie-service
    env: docker
    plan: free
    dockerfilePath: pedagogie-service/Dockerfile
    dockerContext: pedagogie-service
    envVars:
      - key: GITHUB_TOKEN
        sync: false
