server:
  port: ${PORT:8080} # PORT injecté par Render

spring:
  cloud:
    config:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8888 # facultatif, mais inutile ici
  application:
    name: pedagogie-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
